# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Art' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Art
  pod 'MJRefresh', '~> 3.3.1'
  
  pod 'AFNetworking', '~> 3.2.1'
  pod 'YYModel', '~> 1.0.3'
  pod 'Masonry', '~> 1.0.0'
  
  pod 'MBProgressHUD', '~> 0.9.2'
  pod 'SDWebImage', '~> 5.0'
  pod 'AvoidCrash', '~> 2.5.2'

end
